# Generated by Django 5.2.15 on 2026-07-02 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="B2BEnquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("company", models.CharField(blank=True, max_length=200, null=True)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("message", models.TextField()),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "B2B Trade Enquiry",
                "verbose_name_plural": "B2B Trade Enquiries",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="categories/"),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="EditorialSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_id",
                    models.CharField(
                        help_text="e.g. editorial_1, editorial_2",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("tag", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=200)),
                ("highlighted_title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "bullet_points",
                    models.TextField(help_text="One bullet point per line"),
                ),
                (
                    "button_text",
                    models.CharField(default="View Full Collection", max_length=100),
                ),
                (
                    "is_reversed",
                    models.BooleanField(
                        default=False, help_text="Toggle layout alignment (left/right)"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExportCountry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "flag",
                    models.CharField(help_text="Emoji flag e.g. 🇺🇸", max_length=10),
                ),
                ("name", models.CharField(max_length=100)),
                ("tag", models.CharField(default="Active Export", max_length=100)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Export Countries",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="FaqItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=250)),
                ("answer", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="HeritageSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(default="Our Heritage", max_length=100)),
                (
                    "title",
                    models.CharField(default="Five Centuries of", max_length=200),
                ),
                (
                    "highlighted_title",
                    models.CharField(default="Bengali Silk Mastery", max_length=200),
                ),
                (
                    "body_p1",
                    models.TextField(
                        default="Rooted in the handloom heartlands of Bishnupur, Murshidabad, and Shantipur..."
                    ),
                ),
                (
                    "body_p2",
                    models.TextField(
                        default="We operate exclusively as a B2B platform — no retail, no compromise..."
                    ),
                ),
                ("specs_iso", models.CharField(default="9001:2015", max_length=100)),
                ("specs_gi", models.CharField(default="Registered", max_length=100)),
                (
                    "specs_established",
                    models.CharField(default="Est. 2008", max_length=100),
                ),
                (
                    "specs_license",
                    models.CharField(default="Active · 42 Nations", max_length=100),
                ),
                (
                    "button_text",
                    models.CharField(default="Begin B2B Partnership", max_length=100),
                ),
            ],
            options={
                "verbose_name": "Heritage Section",
                "verbose_name_plural": "Heritage Section",
            },
        ),
        migrations.CreateModel(
            name="HeroSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "eyebrow",
                    models.CharField(
                        default="Direct Manufacturer · Export House · OEM · Private Label",
                        max_length=200,
                    ),
                ),
                ("title", models.CharField(default="Bengal's Finest", max_length=200)),
                (
                    "highlighted_title",
                    models.CharField(default="Handloom Sarees", max_length=200),
                ),
                (
                    "description",
                    models.TextField(
                        default="Premium B2B Manufacturer & Global Export Partner for Luxury Boutiques, Fashion Houses & International Retail Chains. Garad · Korial · Baluchari · Jamdani."
                    ),
                ),
                (
                    "primary_cta_text",
                    models.CharField(default="Explore Collection", max_length=100),
                ),
                (
                    "secondary_cta_text",
                    models.CharField(
                        default="Become Wholesale Partner", max_length=100
                    ),
                ),
                ("stats_years", models.CharField(default="52+", max_length=50)),
                ("stats_retailers", models.CharField(default="500+", max_length=50)),
                ("stats_countries", models.CharField(default="42", max_length=50)),
                ("stats_variants", models.CharField(default="12K+", max_length=50)),
            ],
            options={
                "verbose_name": "Hero Section",
                "verbose_name_plural": "Hero Section",
            },
        ),
        migrations.CreateModel(
            name="ProcessStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_number", models.CharField(default="01", max_length=10)),
                ("icon", models.CharField(help_text="Emoji e.g. 🌿", max_length=50)),
                ("label", models.CharField(max_length=100)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="TechnicalMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=150)),
                ("value", models.CharField(max_length=250)),
                (
                    "status_tag",
                    models.CharField(
                        default="Certified",
                        help_text="e.g. Certified, Tested, Verified, Premium, ISO Active",
                        max_length=50,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quote", models.TextField()),
                ("author", models.CharField(max_length=150)),
                ("role", models.CharField(max_length=150)),
                ("location", models.CharField(max_length=150)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="WhyChooseUsCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                (
                    "icon",
                    models.CharField(
                        help_text="Emoji or icon identifier", max_length=50
                    ),
                ),
                ("description", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="core.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Sub Categories",
                "unique_together": {("category", "name")},
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "purity_fabric",
                    models.CharField(
                        default="Grade AAAA Raw Silk",
                        help_text="e.g. Grade AAAA Mulberry Raw Silk — Non-Bleached",
                        max_length=200,
                    ),
                ),
                (
                    "border_specs",
                    models.CharField(
                        default="Traditional Border",
                        help_text="e.g. Intricate 24K Gold Thread Borders",
                        max_length=200,
                    ),
                ),
                (
                    "structural_weight",
                    models.CharField(
                        default="400 Grams",
                        help_text="e.g. 390 Grams Linear Weight Profile",
                        max_length=100,
                    ),
                ),
                (
                    "moq",
                    models.CharField(
                        default="10 Units",
                        help_text="e.g. 25 Units Minimum",
                        max_length=100,
                    ),
                ),
                ("lead_time", models.CharField(default="14-21 Days", max_length=100)),
                ("material", models.CharField(default="Pure Silk", max_length=150)),
                (
                    "image_main",
                    models.ImageField(blank=True, null=True, upload_to="products/"),
                ),
                (
                    "image_hover",
                    models.ImageField(blank=True, null=True, upload_to="products/"),
                ),
                ("is_best_seller", models.BooleanField(default=False)),
                ("is_new_arrival", models.BooleanField(default=False)),
                ("is_handcrafted", models.BooleanField(default=False)),
                ("is_hand_painted", models.BooleanField(default=False)),
                ("is_silk_collection", models.BooleanField(default=False)),
                ("is_cotton_collection", models.BooleanField(default=False)),
                ("is_festive_collection", models.BooleanField(default=False)),
                ("is_sale", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="core.category",
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="core.subcategory",
                    ),
                ),
            ],
        ),
    ]
