# Generated by Django 5.2.15 on 2026-07-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="editorialsection",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Optional luxury cover image for the editorial split screen",
                null=True,
                upload_to="editorials/",
            ),
        ),
    ]
