# Generated by Django 5.2.15 on 2026-07-02 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_editorialsection_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="editorialsection",
            name="video",
            field=models.FileField(
                blank=True,
                help_text="Optional luxury video loop for the editorial split screen",
                null=True,
                upload_to="editorial_videos/",
            ),
        ),
    ]
