# Generated by Django 5.2.15 on 2026-07-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_editorialsection_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_premium",
            field=models.BooleanField(
                default=False, help_text="Show in the Premium section on home page"
            ),
        ),
    ]
