# Generated by Django 5.2.15 on 2026-07-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_product_is_premium"),
    ]

    operations = [
        migrations.CreateModel(
            name="B2BEnquiryCTA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "badge",
                    models.CharField(
                        default="B2B Access Portal · Now Accepting Partners",
                        max_length=200,
                    ),
                ),
                (
                    "title",
                    models.CharField(default="Begin Your Premium", max_length=200),
                ),
                (
                    "highlighted_title",
                    models.CharField(default="Wholesale Partnership", max_length=200),
                ),
                (
                    "description",
                    models.TextField(
                        default="Join 500+ boutiques and luxury retailers sourcing directly from our Bengali silk clusters. Allocations are capacity-limited — contact our procurement team to secure priority access."
                    ),
                ),
                (
                    "whatsapp_button_text",
                    models.CharField(
                        default="✆ Contact Procurement Desk", max_length=150
                    ),
                ),
                (
                    "email_button_text",
                    models.CharField(default="✉ Send Formal Enquiry", max_length=150),
                ),
                (
                    "guarantees",
                    models.TextField(
                        default="Response within 4 hours\nMOQ from 10 units\nFree sample packs\nGlobal shipping included",
                        help_text="One guarantee per line",
                    ),
                ),
            ],
            options={
                "verbose_name": "13b. Wholesale Partnership CTA Section",
                "verbose_name_plural": "13b. Wholesale Partnership CTA Section",
            },
        ),
        migrations.CreateModel(
            name="CategorySectionSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(default="Heritage Portfolios", max_length=100),
                ),
                ("title", models.CharField(default="Explore Saree", max_length=200)),
                (
                    "highlighted_title",
                    models.CharField(default="Categories", max_length=200),
                ),
                (
                    "description",
                    models.TextField(
                        default="Select a category to view active loom allocations, technical specifications, and custom procurement options."
                    ),
                ),
            ],
            options={
                "verbose_name": "03a. Categories Section Header",
                "verbose_name_plural": "03a. Categories Section Header",
            },
        ),
        migrations.CreateModel(
            name="ExportSectionSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(default="Global Reach", max_length=100)),
                ("title", models.CharField(default="Export to", max_length=200)),
                ("highlighted_title", models.CharField(default="42", max_length=200)),
                ("suffix_title", models.CharField(default="Countries", max_length=100)),
                (
                    "description",
                    models.TextField(
                        default="Established shipping infrastructure with full customs documentation for seamless international delivery across luxury markets worldwide."
                    ),
                ),
                (
                    "map_label_title",
                    models.CharField(default="42 Countries", max_length=150),
                ),
                (
                    "map_label_sub",
                    models.CharField(
                        default="Active Export Destinations", max_length=200
                    ),
                ),
            ],
            options={
                "verbose_name": "10a. Global Export Section Header",
                "verbose_name_plural": "10a. Global Export Section Header",
            },
        ),
        migrations.CreateModel(
            name="FaqSectionSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(default="Support Ledger", max_length=100)),
                ("title", models.CharField(default="Frequently Asked", max_length=200)),
                (
                    "highlighted_title",
                    models.CharField(default="Questions", max_length=200),
                ),
                (
                    "description",
                    models.TextField(
                        default="Essential information regarding production capacity, lead times, export documentation, and custom orders."
                    ),
                ),
            ],
            options={
                "verbose_name": "12a. FAQ Section Header",
                "verbose_name_plural": "12a. FAQ Section Header",
            },
        ),
        migrations.CreateModel(
            name="MetricsSectionSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(default="Quality Framework", max_length=100),
                ),
                ("title", models.CharField(default="Technical", max_length=200)),
                ("highlighted_title", models.CharField(default="Loom", max_length=200)),
                ("suffix_title", models.CharField(default="Metrics", max_length=100)),
                (
                    "description",
                    models.TextField(
                        default="Rigorous laboratory-grade standards maintained across all production runs for international B2B compliance and customs clearance."
                    ),
                ),
            ],
            options={
                "verbose_name": "09a. Loom Metrics Section Header",
                "verbose_name_plural": "09a. Loom Metrics Section Header",
            },
        ),
        migrations.CreateModel(
            name="PremiumSectionSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(default="Exclusive Selections", max_length=100),
                ),
                ("title", models.CharField(default="Premium B2B", max_length=200)),
                (
                    "highlighted_title",
                    models.CharField(default="Creations", max_length=200),
                ),
                (
                    "description",
                    models.TextField(
                        default="Explore our most exclusive handloom creations selected for priority showroom allocation. Filtered by category."
                    ),
                ),
            ],
            options={
                "verbose_name": "13a. Premium Products Section Header",
                "verbose_name_plural": "13a. Premium Products Section Header",
            },
        ),
        migrations.CreateModel(
            name="ProcessSectionSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(default="Our Craft", max_length=100)),
                ("title", models.CharField(default="The", max_length=200)),
                (
                    "highlighted_title",
                    models.CharField(default="Manufacturing", max_length=200),
                ),
                ("suffix_title", models.CharField(default="Journey", max_length=100)),
                (
                    "description",
                    models.TextField(
                        default="From raw silk selection to export-ready packaging — every stage is controlled in-house under ISO-certified quality protocols."
                    ),
                ),
            ],
            options={
                "verbose_name": "08a. Manufacturing Process Header",
                "verbose_name_plural": "08a. Manufacturing Process Header",
            },
        ),
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brand_name",
                    models.CharField(
                        default="Jyoti", help_text="e.g. Jyoti", max_length=100
                    ),
                ),
                (
                    "brand_suffix",
                    models.CharField(
                        default="creations", help_text="e.g. creations", max_length=100
                    ),
                ),
                (
                    "site_subtitle",
                    models.CharField(
                        default="Premium B2B Manufacturer", max_length=200
                    ),
                ),
                (
                    "intro_sub",
                    models.CharField(
                        default="Bengal Handloom Heritage Ledger",
                        help_text="Subtext shown during the entrance animation",
                        max_length=200,
                    ),
                ),
                (
                    "showroom_eyebrow",
                    models.CharField(
                        default="Enterprise Allocation Desk", max_length=200
                    ),
                ),
                (
                    "showroom_title",
                    models.CharField(default="B2B Showroom Catalog", max_length=200),
                ),
                (
                    "showroom_desc",
                    models.TextField(
                        default="Explore our active handloom allocations and product listings. Click on any card to view manufacturing technical specifications and initialize bulk procurement inquiries."
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        default="+91 99999 99999",
                        help_text="Public contact number",
                        max_length=50,
                    ),
                ),
                (
                    "whatsapp_number",
                    models.CharField(
                        default="919999999999",
                        help_text="WhatsApp format without + or spaces (e.g. 919999999999)",
                        max_length=50,
                    ),
                ),
                (
                    "email_address",
                    models.EmailField(default="b2b@jyoticreations.com", max_length=254),
                ),
                (
                    "cluster_office",
                    models.CharField(
                        default="Bishnupur Cluster Office", max_length=200
                    ),
                ),
                (
                    "sourcing_hub",
                    models.CharField(
                        default="Murshidabad Sourcing Hub", max_length=200
                    ),
                ),
                (
                    "shipping_desk",
                    models.CharField(
                        default="International Shipping Desk", max_length=200
                    ),
                ),
                (
                    "legal_terms_text",
                    models.CharField(default="B2B Terms", max_length=100),
                ),
                (
                    "legal_privacy_text",
                    models.CharField(default="Privacy Policy", max_length=100),
                ),
                (
                    "legal_gi_text",
                    models.CharField(default="GI Certification", max_length=100),
                ),
                (
                    "legal_export_text",
                    models.CharField(default="Export Compliance", max_length=100),
                ),
            ],
            options={
                "verbose_name": "00. Global Settings & Contact Info",
                "verbose_name_plural": "00. Global Settings & Contact Info",
            },
        ),
        migrations.CreateModel(
            name="TestimonialSectionSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(default="Enterprise Confidence", max_length=100),
                ),
                ("title", models.CharField(default="B2B", max_length=200)),
                (
                    "highlighted_title",
                    models.CharField(default="Client", max_length=200),
                ),
                ("suffix_title", models.CharField(default="Voices", max_length=100)),
                (
                    "description",
                    models.TextField(
                        default="Trusted by luxury boutiques, fashion houses, and international retail chains across four continents."
                    ),
                ),
                (
                    "partner_strip_label",
                    models.CharField(
                        default="Trusted by enterprises across", max_length=200
                    ),
                ),
                (
                    "partner_strip_pills",
                    models.TextField(
                        default="USA · New York\nUK · London\nUAE · Dubai\nFrance · Paris\nSingapore",
                        help_text="One partner location/pill per line",
                    ),
                ),
            ],
            options={
                "verbose_name": "11a. Testimonials Section Header",
                "verbose_name_plural": "11a. Testimonials Section Header",
            },
        ),
        migrations.CreateModel(
            name="TrustMarqueeItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        help_text="e.g. ISO 9001:2015 Certified", max_length=150
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "02. Trust Ribbon Marquee Item",
                "verbose_name_plural": "02. Trust Ribbon Marquee Items",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="WhyChooseUsSectionSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(default="Our Advantage", max_length=100)),
                (
                    "title",
                    models.CharField(
                        default="Why Global Buyers Choose", max_length=200
                    ),
                ),
                (
                    "highlighted_title",
                    models.CharField(default="Jyoticreations", max_length=200),
                ),
                (
                    "description",
                    models.TextField(
                        default="From direct loom access to private label programs — we are the complete B2B manufacturing partner for luxury saree commerce worldwide."
                    ),
                ),
                ("stat1_number", models.CharField(default="100%", max_length=50)),
                (
                    "stat1_label",
                    models.CharField(default="Sourcing Transparency", max_length=100),
                ),
                ("stat2_number", models.CharField(default="ISO", max_length=50)),
                (
                    "stat2_label",
                    models.CharField(default="9001:2015 Audited", max_length=100),
                ),
            ],
            options={
                "verbose_name": "06a. Why Choose Us Section Header",
                "verbose_name_plural": "06a. Why Choose Us Section Header",
            },
        ),
        migrations.AlterModelOptions(
            name="b2benquiry",
            options={
                "verbose_name": "14. B2B Trade Enquiry Received",
                "verbose_name_plural": "14. B2B Trade Enquiries Received",
            },
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "verbose_name": "03b. Saree Category",
                "verbose_name_plural": "03b. Saree Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="editorialsection",
            options={
                "verbose_name": "05. Editorial Split-Screen Panel",
                "verbose_name_plural": "05. Editorial Split-Screen Panels",
            },
        ),
        migrations.AlterModelOptions(
            name="exportcountry",
            options={
                "ordering": ["order"],
                "verbose_name": "10b. Global Export Country",
                "verbose_name_plural": "10b. Global Export Countries",
            },
        ),
        migrations.AlterModelOptions(
            name="faqitem",
            options={
                "ordering": ["order"],
                "verbose_name": "12b. FAQ Item",
                "verbose_name_plural": "12b. FAQ Items",
            },
        ),
        migrations.AlterModelOptions(
            name="heritagesection",
            options={
                "verbose_name": "07. Heritage & History Section",
                "verbose_name_plural": "07. Heritage & History Section",
            },
        ),
        migrations.AlterModelOptions(
            name="herosection",
            options={
                "verbose_name": "01. Hero Banner Section",
                "verbose_name_plural": "01. Hero Banner Section",
            },
        ),
        migrations.AlterModelOptions(
            name="processstep",
            options={
                "ordering": ["order"],
                "verbose_name": "08b. Manufacturing Process Step",
                "verbose_name_plural": "08b. Manufacturing Process Steps",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "verbose_name": "04. Product & Catalog Sourcing Entry",
                "verbose_name_plural": "04. Products & Catalog Sourcing Entries",
            },
        ),
        migrations.AlterModelOptions(
            name="subcategory",
            options={
                "verbose_name": "03c. Saree Sub-Category",
                "verbose_name_plural": "03c. Saree Sub-Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="technicalmetric",
            options={
                "ordering": ["order"],
                "verbose_name": "09b. Loom Metrics Specification",
                "verbose_name_plural": "09b. Loom Metrics Specifications",
            },
        ),
        migrations.AlterModelOptions(
            name="testimonial",
            options={
                "ordering": ["order"],
                "verbose_name": "11b. Testimonials Customer Review",
                "verbose_name_plural": "11b. Testimonials Customer Reviews",
            },
        ),
        migrations.AlterModelOptions(
            name="whychooseuscard",
            options={
                "ordering": ["order"],
                "verbose_name": "06b. Why Choose Us Advantage Card",
                "verbose_name_plural": "06b. Why Choose Us Advantage Cards",
            },
        ),
    ]
