# Generated by Django 5.2.15 on 2026-07-02 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_b2benquirycta_categorysectionsettings_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "verbose_name": "03b. Category",
                "verbose_name_plural": "03b. Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="subcategory",
            options={
                "verbose_name": "03c. Sub-Category",
                "verbose_name_plural": "03c. Sub-Categories",
            },
        ),
    ]
