# Generated by Django 5.2.15 on 2026-07-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_category_options_alter_subcategory_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Partner logo or emblem image",
                        null=True,
                        upload_to="partners/",
                    ),
                ),
                (
                    "is_top_highlight",
                    models.BooleanField(
                        default=False,
                        help_text="Highlight this partner at the top of the list (Max 10)",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "15b. Global Partner",
                "verbose_name_plural": "15b. Global Partners",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="PartnersSectionSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(default="Enterprise Network", max_length=100),
                ),
                ("title", models.CharField(default="Our Global", max_length=200)),
                (
                    "highlighted_title",
                    models.CharField(default="B2B Partners", max_length=200),
                ),
                (
                    "description",
                    models.TextField(
                        default="We collaborate with premier fashion boutiques, luxury retail networks, and international sourcing agencies."
                    ),
                ),
            ],
            options={
                "verbose_name": "15a. Partners Section Header",
                "verbose_name_plural": "15a. Partners Section Header",
            },
        ),
    ]
