# Generated by Django 5.2.15 on 2026-07-10 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_partner_partnerssectionsettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="CRMClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                ("contact_person", models.CharField(max_length=150)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(max_length=50)),
                (
                    "location",
                    models.CharField(
                        help_text="e.g. New York, USA or Mumbai, India", max_length=150
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "CRM Client",
                "verbose_name_plural": "CRM Clients",
            },
        ),
        migrations.CreateModel(
            name="CRMVendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. Bishnupur Weaver Cluster A", max_length=150
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("cluster", models.CharField(default="Bishnupur", max_length=150)),
                (
                    "active_capacity",
                    models.CharField(
                        default="50 units/month",
                        help_text="Loom monthly capacity estimate",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "CRM Vendor/Weaver",
                "verbose_name_plural": "CRM Vendors/Weavers",
            },
        ),
        migrations.AddField(
            model_name="b2benquiry",
            name="custom_branding_requested",
            field=models.BooleanField(
                default=False,
                help_text="Checked if client requested custom tags/embroidery",
            ),
        ),
        migrations.CreateModel(
            name="CRMOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending / WhatsApp Booked"),
                            ("Production", "In Loom Production"),
                            ("Shipped", "Shipped / In Transit"),
                            ("Delivered", "Delivered"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Pending",
                        max_length=50,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("Pending", "Unpaid"),
                            ("Partial", "Partially Paid"),
                            ("Paid", "Fully Paid"),
                        ],
                        default="Pending",
                        max_length=50,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Negotiated total order amount",
                        max_digits=12,
                    ),
                ),
                (
                    "custom_branding_requested",
                    models.BooleanField(
                        default=False,
                        help_text="Did the buyer request custom tags/embroidery?",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Shipment details, specific weave pattern requests, etc.",
                        null=True,
                    ),
                ),
                ("order_date", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="core.crmclient",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Assigned Weaver Cluster",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="core.crmvendor",
                    ),
                ),
            ],
            options={
                "verbose_name": "CRM Order",
                "verbose_name_plural": "CRM Orders",
                "ordering": ["-order_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="CRMOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Negotiated unit price",
                        max_digits=10,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.crmorder",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.product"
                    ),
                ),
            ],
            options={
                "verbose_name": "CRM Order Item",
                "verbose_name_plural": "CRM Order Items",
            },
        ),
    ]
