# Generated by Django 5.2.15 on 2026-07-10 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_crmclient_crmvendor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="video",
            field=models.FileField(
                blank=True,
                help_text="Optional product demonstration video loop",
                null=True,
                upload_to="product_videos/",
            ),
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="products/gallery/")),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order in which images appear in gallery"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_images",
                        to="core.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Sub-Image",
                "verbose_name_plural": "Product Sub-Images",
                "ordering": ["order"],
            },
        ),
    ]
