# Generated by Django 5.2.16 on 2026-08-10 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_product_video_productimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="b2benquirycta",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Uncheck to hide this section on the client homepage",
            ),
        ),
        migrations.AddField(
            model_name="categorysectionsettings",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Uncheck to hide this section on the client homepage",
            ),
        ),
        migrations.AddField(
            model_name="editorialsection",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Uncheck to hide this editorial panel on the client homepage",
            ),
        ),
        migrations.AddField(
            model_name="exportsectionsettings",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Uncheck to hide this section on the client homepage",
            ),
        ),
        migrations.AddField(
            model_name="faqsectionsettings",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Uncheck to hide this section on the client homepage",
            ),
        ),
        migrations.AddField(
            model_name="heritagesection",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Uncheck to hide this section on the client homepage",
            ),
        ),
        migrations.AddField(
            model_name="herosection",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Uncheck to hide this section on the client homepage",
            ),
        ),
        migrations.AddField(
            model_name="metricssectionsettings",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Uncheck to hide this section on the client homepage",
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Uncheck to hide this partner from the client Partners page",
            ),
        ),
        migrations.AddField(
            model_name="partnerssectionsettings",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Uncheck to deactivate Partners page content (also controlled by Global Settings → partners_page_active)",
            ),
        ),
        migrations.AddField(
            model_name="premiumsectionsettings",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Uncheck to hide this section on the client homepage",
            ),
        ),
        migrations.AddField(
            model_name="processsectionsettings",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Uncheck to hide this section on the client homepage",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="crm_portal_active",
            field=models.BooleanField(
                default=True,
                help_text="If inactive: hide CRM Portal link in the footer (login route still works for staff)",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="partners_page_active",
            field=models.BooleanField(
                default=True,
                help_text="If inactive: hide Partners from header/footer and return 404 on /partners/",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="showroom_page_active",
            field=models.BooleanField(
                default=True,
                help_text="If inactive: hide Showroom from header/footer and return 404 on /showroom/",
            ),
        ),
        migrations.AddField(
            model_name="testimonialsectionsettings",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Uncheck to hide the Client Voices section on the homepage",
            ),
        ),
        migrations.AddField(
            model_name="whychooseussectionsettings",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Uncheck to hide this section on the client homepage",
            ),
        ),
    ]
